### ISSUE TITLE
Need to work out how get HA to create climate.myspa without this.

### ISSUE THREAD

**Issue by wayne-love** [wayne-love/ESPySpa#49]
```
   json["name"]="";  ///TODO - Need to work out how get HA to create climate.myspa without this.
```

In file lib/HAAutoDiscovery/HAAutoDiscovery.cpp
https://github.com/wayne-love/sn_esp32/blob/87546d2f59ccdfaabb400f04ebec4559b302e677/lib/HAAutoDiscovery/HAAutoDiscovery.cpp#L115

**Comment by lucasnz** [comment]
Now that we don't need to support the old set up, we can delete:
json["name"]="";  ///TODO #49 - Need to work out how get HA to create climate.myspa without this.

If we change the following in main:
config.displayName = "Heat Set Point";
to:
config.displayName = "";

**Comment by lucasnz** [comment]
I think we can close this now
